name: mars3888
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab=2.1
  - numpy
  - pip
  - pandas
  - scipy
  - netCDF4
  - compilers
  - gfortran
  - python-graphviz
  - seaborn
  - scikit-image
  - scikit-learn=0.23
  - h5py
  - xarray
  - cmocean
  - shapely
  - cartopy
  - dask
  - zarr
  - pymt
  - pip:
      - pymannkendall==1.2 
